# Generated by Django 4.2.4 on 2023-08-18 00:36

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_tag_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF",
                help_text="HEX цвета подставляеться автоматически",
                image_field=None,
                max_length=50,
                samples=None,
                verbose_name="Цвет",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                help_text="Должен быть уникальным",
                max_length=200,
                unique=True,
                verbose_name="Slug тега",
            ),
        ),
    ]
