version: '3.3'

volumes:
  static:
  media:
  pg:

services:
  db:
    image: postgres:13
    volumes:
      - pg:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    depends_on: 
      - db
    image: fklska/foodgram_backend:latest
    volumes:
      - static:/static/
      - media:/media/
    env_file:
      - .env

  frontend:
    image: fklska/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
  
  nginx:
    depends_on:
      - db
      - frontend
      - backend
    image: nginx:1.19.3
    env_file: .env
    ports:
      - "443:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/media/
